Repository grafana/grafana-iot-twinmaker-app, pull requests merged in 2024-06, with the labels that each got.

#283 chore(release-1.15.0): support dynamic scenes launch
  .npmrc
  CHANGELOG.md
  cypress/integration/something.ts
  cypress/tsconfig.json
  package.json
  pkg/plugin/twinmaker/handler.go
  src/datasource/components/ConfigEditor.test.tsx
  src/panels/scene-viewer/SceneViewer.tsx
  yarn.lock
Labels: changelog

#282 Remove relative path info from executable field
  go.mod
  go.sum
  src/datasource/plugin.json
Labels: type/bug, go, type/chore

#288 Add nested plugin to app includes
  src/plugin.json
Labels: type/chore
